### PR TITLE
Add hosts blacklist to DB_Copy App

### PR DESCRIPTION
**Pull request by radome**
- Prevent running commands on hosts that aren't accessible from our servers using a configurable blacklist
- Refactor the use of global variables in db_app

**Note:** Requires https://github.com/Ensembl/ensembl-prodinf-core/pull/118

### CODE REVIEW

**Comment by radome** [comment]
> What's the associated bug here?

In general, preventing to run commands on hosts that are not accessible speeds up the response. In this case also, we have scripts that use the `/hosts` endpoint to monitor servers every second. That's flooding the logs with errors which makes hard to track other things and it's possibly the cause for some of the timeouts we experienced.

**Comment by marcoooo** [comment]
> > What's the associated bug here?
> 
> In general, preventing to run commands on hosts that are not accessible speeds up the response. In this case also, we have scripts that use the `/hosts` endpoint to monitor servers every second. That's flooding the logs with errors which makes hard to track other things and it's possibly the cause for some of the timeouts we experienced.

Ok, thank you for the explanation @radome !

**Comment by thomasmaurel** [comment]
@radome: Does that mean that we need to find and list all the new hosts and put them in the config file? There are quite a lot of new servers

**Comment by radome** [comment]
> @radome: Does that mean that we need to find and list all the new hosts and put them in the config file? There are quite a lot of new servers

Theoretically, yes. Practically, so far only two servers we don't have access to are being repeatedly queried by a script, so I'd say we start with those two and we keep adding others as soon as they start flooding the logs.

**Comment by thomasmaurel** [comment]
> > @radome: Does that mean that we need to find and list all the new hosts and put them in the config file? There are quite a lot of new servers
> 
> Theoretically, yes. Practically, so far only two servers we don't have access to are being repeatedly queried by a script, so I'd say we start with those two and we keep adding others only when they start flooding the logs.

Sure that make sense 👍

**Pull request merged**
